# Generated by Django 4.1 on 2023-04-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("genres", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="movies",
        ),
    ]
