# Generated by Django 4.1 on 2023-04-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("genres", "0004_remove_genre_movies"),
        ("movies", "0004_movie_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(related_name="movies", to="genres.genre"),
        ),
    ]
